spring:
  datasource-quartzapi:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz
    username: root
    password: test
    hikari:
      pool-name: QuartzApiHikariCP
      maximum-pool-size: 1
      connection-timeout: 30000
      idleTimeout: 30000
      maxLifetime: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
