spring:
  datasource-quartzapi:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz
    username: root
    password: test
    hikari:
      pool-name: QuartzApiHikariCP
      connection-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 1
      leak-detection-threshold: 1000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          connection:
            handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE