spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz
    username: root
    password: test
    hikari:
      pool-name: QuartzHikariCP
      maximum-pool-size: 1
      connection-timeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  quartz:
    scheduler-name: crontab-scheduler
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            instanceName: ApiQuartzClusteredScheduler
          threadPool:
            threadCount: 25
            threadPriority: 5
          jobStore:
            isClustered: true
  #            class: org.quartz.impl.jdbcjobstore.JobStoreTX
  #            dataSource: spring.datasource
  #            clusterCheckinInterval: 20000
  mvc:
    log-request-details: true
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 80
  error:
    whitelabel:
      enabled: false
    path: /error
    include-exception: true
    include-message: always
    include-stacktrace: never
    include-binding-errors: never