spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://localhost:3306/quartz
    username: root
    password: test
  quartz:
    scheduler-name: common
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            instanceName: ApiQuartzClusteredScheduler
          threadPool:
            threadCount: 25
            threadPriority: 5
          jobStore:
            isClustered: true
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            dataSource: spring.datasource
#            clusterCheckinInterval: 20000
logging:
  level:
    org.spring.framework.web.filter.CommonsRequestLoggingFilter: DEBUG